[server]
max_tps = 50.0
update_rate = 20.0

[client]
username = "ExampleUsername"
metaverse_provider = ""

[glyphs]
font_path = "/usr/share/fonts/mononoki/mononoki-Regular.ttf"
sdf_scale = 2.0
sdf_border = 1.0
sdf_range = 4.0

[renderer.debug]
enabled = true
draw_lights = true
draw_transforms = true

[ui]
script_path = "ui_script.wasm"
panel_impl = "PanelImpl"
