[server]
max_tps = 50.0
update_rate = 20.0

[client]
username = "ExampleUsername"
metaverse_provider = ""

[displays.sdl]
camera_speed = 5.0

[glyphs]
font_path = "mononoki-Regular.ttf"
sdf_scale = 2.0
sdf_border = 1.0
sdf_range = 4.0

[renderer]

# Calls vkQueueWaitIdle after every submit.
# Stops Monado from flickering, but stalls the CPU.
queue_stall = false

[renderer.debug]
enabled = true
draw_lights = true
draw_transforms = true
draw_pointers = true

[ui]
script_path = "ui_script.wasm"
