# Copyright (c) 2020-2021 the Mondradiko contributors.
# SPDX-License-Identifier: LGPL-3.0-or-later

name = "PointLightComponent"
storage_type = "component"
internal_name = "PointLightComponent"
internal_header = "core/components/scriptable/PointLightComponent.h"

[methods]

  [methods.setIntensity]
  param_list = ["r", "g", "b"]

    [methods.setIntensity.params]
    r = "double"
    g = "double"
    b = "double"
