# Copyright (c) 2020-2021 the Mondradiko contributors.
# SPDX-License-Identifier: LGPL-3.0-or-later

name = "Transform"
storage_type = "component"
internal_name = "TransformComponent"
internal_header = "core/components/TransformComponent.h"

[methods]

  [methods.getX]
  brief = "Retrieves the X coordinate of this Transform."
  return = "double"

  [methods.getY]
  brief = "Retrieves the Y coordinate of this Transform."
  return = "double"

  [methods.getZ]
  brief = "Retrieves the Z coordinate of this Transform."
  return = "double"

  [methods.setPosition]
  brief = "Sets the position of this Transform."
  param_list = ["x", "y", "z"]

    [methods.setPosition.params]
    x = "double"
    y = "double"
    z = "double"

  [methods.getRotationW]
  brief = "Retrieves the W rotation component of this Transform's Quarternion."
  return = "double"

  [methods.getRotationX]
  brief = "Retrieves the X rotation component of this Transform's Quarternion."
  return = "double"

  [methods.getRotationY]
  brief = "Retrieves the Y rotation component of this Transform's Quarternion."
  return = "double"

  [methods.getRotationZ]
  brief = "Retrieves the Z rotation component of this Transform's Quarternion."
  return = "double"
  
  [methods.setRotation]
  brief = "Sets the Quarternion rotation of this Transform."
  param_list = ["w", "x", "y", "z"]

    [methods.setRotation.params]
    w = "double"
    x = "double"
    y = "double"
    z = "double"
