# Copyright (c) 2020-2021 the Mondradiko contributors.
# SPDX-License-Identifier: LGPL-3.0-or-later

name = "Transform"
storage_type = "component"
internal_name = "TransformComponent"
internal_header = "core/components/TransformComponent.h"

[methods]

  [methods.getX]
  brief = "Retrieves the X coordinate of this Transform."
  return = "double"

  [methods.getY]
  brief = "Retrieves the Y coordinate of this Transform."
  return = "double"

  [methods.getZ]
  brief = "Retrieves the Z coordinate of this Transform."
  return = "double"

  [methods.setPosition]
  brief = "Sets the position of this Transform."
  param_list = ["x", "y", "z"]

    [methods.setPosition.params]
    x = "double"
    y = "double"
    z = "double"
