# Copyright (c) 2020 the Mondradiko contributors.
# SPDX-License-Identifier: LGPL-3.0-or-later

name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
        matrix:
          include:
            # - extra_cmake_args: "-DUSE_PKGCONFIG=ON"
            - extra_cmake_args: "-DUSE_PKGCONFIG=OFF"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install ninja-build tool
        uses: mondradiko/gha-setup-ninja@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64

      - name: apt
        if: runner.os == 'Linux'
        run: sudo apt install libwayland-dev libxrandr-dev

      - name: cached vcpkg runtime
        if: runner.os == 'Linux'
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('.git/modules/vcpkg/HEAD') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('vcpkg/.git/HEAD') }}
          path: vcpkg/vcpkg

      - name: Compile
        shell: bash
        run: |
          mkdir builddir
          pushd builddir
          cmake -GNinja .. ${{ matrix.extra_cmake_args }}
          ninja
          popd

      - name: Verify
        run: |
          ./builddir/client/mondradiko-client --version || true
          ./builddir/server/mondradiko-server --version || true
          ./builddir/bundler/mondradiko-bundler --version || true
